--liquibase formatted sql

--changeset rashidul:1
CREATE TABLE IF NOT EXISTS employee_table (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   employee_id UUID,
   table_id BIGINT,
   CONSTRAINT pk_employee_table PRIMARY KEY (id)
);