--liquibase formatted sql

--changeset rashidul:1
CREATE TABLE IF NOT EXISTS foods (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   description VARCHAR(1000),
   price INTEGER,
   discount_type INTEGER,
   discount INTEGER,
   discount_price INTEGER,
   image VARCHAR(255),
   image_url VARCHAR(255),
   CONSTRAINT pk_foods PRIMARY KEY (id)
);