--liquibase formatted sql

--changeset rashidul:1
CREATE TABLE IF NOT EXISTS tables (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   table_number VARCHAR(255),
   number_of_seats INTEGER,
   is_occupied BOOLEAN,
   image VARCHAR(255),
   image_url VARCHAR(255),
   CONSTRAINT pk_tables PRIMARY KEY (id)
);