--liquibase formatted sql

--changeset rashidul:1
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price INTEGER NOT NULL,
    total_price INTEGER NOT NULL,
    food_id BIGINT,
    order_id UUID,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_item_food FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE SET NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);