--liquibase formatted sql

--changeset rashidul:1
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255) NOT NULL,
    expiry TIMESTAMP NOT NULL,
    user_id UUID,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
